### ISSUE TITLE
The authenticity of host 'github.com (192.30.253.113)' can't be established.

### ISSUE THREAD

**Issue by wKovacs64** [cypress-io/circleci-orb#101]
I'm trying to implement the ["release" example](https://github.com/cypress-io/circleci-orb/blob/38092878a05f6a47d1b007e30e460c1b2b48602b/docs/examples.md#release) as shown in the orb docs, but when `semantic-release` tries to push the new tag to GitHub, it cannot verify the host identity and hangs at this prompt:

```
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? 
```

I'm guessing `StrictHostKeyChecking` is enabled and there is just no entry for it in `~/.ssh/known_hosts` in the container (`cypress/base:10` in my case). It works fine if I use another image for running `semantic-release` (e.g. `circleci/node:lts`). Is this something that can be resolved at the Cypress orb or container level? Or am I doing something incorrectly?

Thanks!

**Comment by bahmutov** [comment]
Hmm not sure, I remember seeing this error a looooong time ago, but have not hit it in our orb projects

**Comment by wKovacs64** [comment]
Huh, weird. I just tried it on a fresh project and it happened there, too. Maybe GitHub added a new server lately or something? You could disable `StrictHostKeyChecking` in the image (a potential security risk, but I _think_ that's what Circle, Travis, and others do) rather than try to keep `known_hosts` up to date.

Sorry, I don't know much about Docker or Orb authoring so probably no PR from me here. 😛

**Comment by bahmutov** [comment]
Interesting - how does your project authenticate with GitHub from Circle? I thought that by adding the project from CircleCI it connects to GitHub repo using SSH automatically, so the connection should be established correctly

**Comment by wKovacs64** [comment]
Authentication is done via the `GH_TOKEN` environment variable (a GitHub personal access token). I'm basically copy-pasting the [semantic-release CI configuration](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#ci-configuration) docs and the Cypress orb [release example](https://github.com/cypress-io/circleci-orb/blob/38092878a05f6a47d1b007e30e460c1b2b48602b/docs/examples.md#release), nothing too out of the ordinary (I don't think?).

**Comment by bahmutov** [comment]
hmm, you did not do in CircleCI "add project"? I mean all my projects use the same workflow:
- on CircleCI add project (which should create GitHub SSH key for Circle to access GitHub)
- do semantic release and set `GH_TOKEN` and `NPM_TOKEN` on CircleCI

That's it, don't know why anything else would be necessary, maybe your `GH_TOKEN` is somehow incorrect?

**Comment by wKovacs64** [comment]
Yep, I did all that. My token is correct and the Circle SSH key is visible in the GitHub repo (and semantic-release works after replacing the `cypress/base-10` executor with the `circleci/node:lts` docker image in my Circle config, no other changes). 🤷‍♂️ 

Here's a fresh reproduction:
https://github.com/wKovacs64/cypress-orb-semantic-release

**Comment by Jerska** [comment]
The fix for me was to change my `repository.url` field in my `package.json` to use the `https` version of my repo instead of the `git+ssh` one.

**Comment by wKovacs64** [comment]
Nice find, @Jerska! My minimal reproduction of the problem did not include a `repository` field at all, so I added a `git+ssh` URL like all my other repos and that failed as you predicted. I changed it to `https` and that worked.

I guess I'll close this, although that seems like a strange requirement. 🤔

**Comment by BBlackwo** [comment]
For me I had to manually execute these steps before running `semantic-release`:

```yml
- run: mkdir -p ~/.ssh      
- run: ssh-keyscan github.com >> ~/.ssh/known_hosts
```

This was based off of the Circle CI docs: https://circleci.com/docs/2.0/gh-bb-integration/#establishing-the-authenticity-of-an-ssh-host

See PR https://github.com/btroncone/ngrx-store-localstorage/pull/193
