### ISSUE TITLE
Question: Can this be used with a database image?

### ISSUE THREAD

**Issue by charlex** [cypress-io/circleci-orb#111]
I'm currently using two images to do my e2e tests:

1. Image to run PostgreSQL
2: Image to build my app and run Cypress

Can this orb be used in conjunction with Postgres? 

I followed this setup guide for CircleCI to pull this off:

https://circleci.com/docs/2.0/postgres-config/

**Comment by charlex** [comment]
I decided to just eject:

https://github.com/cypress-io/circleci-orb#ejecting

**Comment by bahmutov** [comment]
yeah, if you need to control several images, this goes beyond a simple orb's purpose like this one

**Comment by charlex** [comment]
@bahmutov Thank you! 

I don't think it's the most important thing in the world, because this Orb provides (at least) a great starting point to eject from, but I do think that having support for multiple images will be common enough that many people would benefit from this as Orbs take more flight.

**Comment by bahmutov** [comment]
agree with you @charlex  - I would love to see your repo to see what you need and how the circle config looks for you
