### ISSUE TITLE
Changing working directory

### ISSUE THREAD

**Issue by jesseschutt** [cypress-io/circleci-orb#113]
Hello!

I have a project that is structured as follows:

```
.circleci
  - .config.yaml
frontend
  - package.json
  - src
    - js application files
  - tests
API-related files ...
```

Is it possible to trigger a running of the cypress tests on Circle using this structure? And if so, could anyone point me in the direction?

Thank you!

**Comment by bahmutov** [comment]
I’m not sure I understand- is it not working? The circleci should pick up either circle.yml or .circle config and run in the root of the project the same way

**Comment by jesseschutt** [comment]
Since the `package.json` file is not at the root of the project it is not available when CircleCI attempts to install the dependencies. I need to `cd frontend` before attempting to run any tests or builds.

Does that make sense?

**Comment by bahmutov** [comment]
Oh I see, it wasn’t clear from the file example. I guess you could use working directory command option for each command ... but I guess this would also affect caching. Hmm probably this orb could be a starting point for the right config file

**Comment by maximgeerinck** [comment]
Having same issue

**Comment by SethGreylyn** [comment]
I've also run into this issue. My project has `frontend` and `api` sibling directories, each with their own `yarn.lock` files, their own `package.json`s, etc.

I've tried the following configuration:
`workflows:
  version: 2.1
  e2e-tests:
    jobs:
      - cypress/run:
          working_directory: ~/path/to/frontend
`
But this does not work; CircleCI complains that `working_directory` is an unexpected argument.

How can one set the working directory for "each command" of the orb?

**Comment by bahmutov** [comment]
ok, I agree - this would be a very nice feature to add. Do you mind adding it (in the src/orb.yml file) and then opening a pull request?
