### ISSUE TITLE
npx wait-on failing

### ISSUE THREAD

**Issue by Sdwz** [cypress-io/circleci-orb#119]
Greetings,

Since this morning, we have failure on Circle CI due to `npx wait-on`.

Here is the error message :

```
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module '/root/.npm/_npx/1011/lib/node_modules/wait-on/node_modules/core-js/scripts/postinstall'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! core-js@2.6.6 postinstall: `node scripts/postinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the core-js@2.6.6 postinstall script. 
```
Thanks for your input.

Cheers

**Comment by bahmutov** [comment]
can you try it again - seems it is just a temp network hiccup, the wait-on has passed several times in this project https://circleci.com/gh/bahmutov/demo-battery-api/50

**Comment by Sdwz** [comment]
This is still happening right now.
```
#!/bin/bash -eo pipefail
npx wait-on http://localhost:3000
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module '/root/.npm/_npx/917/lib/node_modules/wait-on/node_modules/core-js/scripts/postinstall'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! core-js@2.6.7 postinstall: `node scripts/postinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the core-js@2.6.7 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-20T23_38_40_569Z-debug.log
Install for wait-on@latest failed with code 1
Exited with code 1
```

**Comment by Sdwz** [comment]
Also your project doesn't use the wait-on config, so npx wait-on isn't triggered.

You'll have to have something similar to reproduce the issue :

```
 cypress/run:
          build: 'yarn build'
          start: 'yarn start'
          **wait-on: 'http://localhost:3000'**
          yarn: true
          store_artifacts: true
```

**Comment by bahmutov** [comment]
Hmm you are right, I need to check it more carefully

**Comment by Sdwz** [comment]
Thanks !

**Comment by bahmutov** [comment]
@Sdwz how about this project that uses `wait-on` https://circleci.com/gh/bahmutov/react-server-example/1 ?

**Comment by Sdwz** [comment]
Well mine still breaks with the above configuration. I have 0 idea what I do wrong, even connected to the container on circle the command breaks on its own.

**Comment by Sdwz** [comment]
Wanna add I had no issue Friday.

**Comment by JouiiinO** [comment]
Same thing here, got exactly the same error right now. It was fine yesterday.

**Comment by bahmutov** [comment]
yeah, hard to say why this would fail - maybe because this Orb just uses the latest version of `wait-on` - can I suggest installing `wait-on` as NPM dependency in your project? I will reopen this issue, even if I don't know the answer to this problem.

**Comment by JouiiinO** [comment]
Weird thing is wait-on hasn't been updated since November last year: https://github.com/jeffbski/wait-on/releases

**Comment by Sdwz** [comment]
Somehow it's working fine this morning.

Maybe one of the deps got fucked up

**Comment by JouiiinO** [comment]
I can confirm that it's fine now, without any update on my side.

**Comment by SUSANO-O** [comment]
hello, how can I configure wait-on to work in cypress. thanks for your help

**Comment by bahmutov** [comment]
@SUSANO-O https://github.com/cypress-io/circleci-orb/blob/master/docs/examples.md#wait-for-server-to-respond

**Comment by seenickcode** [comment]
Hi guys, I'm getting this myself. Maybe I need to clear some kind of cache? Here's my config:

```
version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          start: FSF_ENV_NAME=stg npm start
          command: npx cypress run --config baseUrl=http://localhost:3000
          wait-on: 'http://localhost:3000'
```

**Comment by maxstralka** [comment]
It's also failing for me out of the blue. Here's the CircleCI output: 

```
#!/bin/bash -eo pipefail
npx wait-on http://localhost:3000
npx: installed 15 in 6.267s
Cannot find module 'lodash/fp'

Exited with code exit status 1
```

**Comment by maxstralka** [comment]
Nevermind. Seem to have been a network issue. The circle CI job runs without a problem a few hours later...
