### ISSUE TITLE
Orb cypress-io/cypress@1.0.0 not loaded. 

### ISSUE THREAD

**Issue by i-am-sanguine** [cypress-io/circleci-orb#130]
Please help
I am using cypress and circleci for the first time:

my build returned this error:

``` Orb cypress-io/cypress@1.0.0 not loaded. To use this orb, an organization admin must opt-in to using third party orbs in Organization Security settings.```

Here is my config.yml file:

```
version: 2.1
orbs:
  cypress-io: cypress-io/cypress@1.0.0
workflows:
  build:
    jobs:
      - cypress/run```

**Comment by bahmutov** [comment]
1) https://github.com/cypress-io/circleci-orb#how-to-enable
2) you imported the orb "cypress-io/cypress" under name "cypress-io" right, so your job should be "- cypress-io/run"
3) the orb is already at version 1.7.0 so I suggest you start with "cypress-io/cypress@1", get it to work and then lock to precise version
