### ISSUE TITLE
Possible to use this orb with ruby on rails app?

### ISSUE THREAD

**Issue by zanthorn** [cypress-io/circleci-orb#139]
I have been attempting to use this orb with a Ruby on Rails project. However, since the cypress base docker images do not have the rails binary installed, doing `start: rails server` fails and the app never starts up. 

What is the best approach to solve this? Custom docker image that includes rails and other dependencies to run the app?

**Comment by bahmutov** [comment]
I think this should be possible, you just need to specify a custom executor with a different Docker image - something that has both ruby and node - find them here https://circleci.com/docs/2.0/docker-image-tags.json

- executor example https://github.com/cypress-io/circleci-orb/blob/master/docs/examples.md#custom-executor

@zanthorn I would be interested in an actual Ruby example. Is there a tiny "hello world" example that I could copy as official example?

**Comment by zanthorn** [comment]
Ok I can easily find an image with ruby and node, but is there anything else the cypress base image has that would need to be included on top of those? I'll give the executor suggestion a shot and report back.

This looks like a nice small rails app that could be used for testing: https://github.com/faradayio/rails_hello

**Comment by bahmutov** [comment]
I think you will need to use node + rails + browsers image there to install all OS libraries that Cypress needs (see https://docs.cypress.io/guides/guides/continuous-integration.html#Dependencies)

**Comment by bahmutov** [comment]
@zanthorn I have made a fork of that repo at https://github.com/bahmutov/rails_hello and locally it runs Cypress test fine:
- `rails server` in one terminal
- `npx cypress run` in another

I have created [circle.yml](https://github.com/bahmutov/rails_hello/blob/master/circle.yml) that seems to almost work - except the server is not started with `rails server`. Instead is says in https://circleci.com/gh/bahmutov/rails_hello/7

```
#!/bin/bash -eo pipefail
rails server
Usage:
  rails new APP_PATH [options]

Options:
  -r, [--ruby=PATH]                                      # Path to the Ruby binary of your choice
...
```

Why does it think I am trying to create a new app?
```

**Comment by zanthorn** [comment]
Hmm not sure why `rails server` isn't starting up with that. I did finally get this working with your suggestion of an executor with a different image that contains ruby/node. Here is what I needed to add in my workflows:

```
      - cypress/run:
          build: bundle install
          yarn: true
          executor: ruby 
          start: cd ~/project && rails server
          cache-key: yarn-v2
          wait-on: http://localhost:3000
```
