### ISSUE TITLE
Normalize parameter names

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/circleci-orb#148]
right now some parameters are using `-` and some `_`

<img width="675" alt="Screen Shot 2019-07-11 at 10 43 12 AM" src="https://user-images.githubusercontent.com/2212006/61060597-c70fd100-a3c8-11e9-893c-9f16b5a133b2.png">
 
Unfortunately, this will be a breaking change, unless we keep both and deprecate ...

**Comment by kylemh** [comment]
https://github.com/cypress-io/circleci-orb/pull/238#issuecomment-597762926

Prefer `-` to `_`

Is this ready to be worked on, or are you trying to avoid breaking changes until some other feature?

**Comment by bahmutov** [comment]
I would prefer to hold off. One big issue is that we don’t have full end to end testing to prevent accidental breaking changes
