### ISSUE TITLE
Pass variable/output from previous job

### ISSUE THREAD

**Issue by aequasi** [cypress-io/circleci-orb#170]
As a user, I would like to be able to pass the output from one job, to the cypress/run job.

### Use Case

One of our build steps prepares a [zeit now](https://zeit.co) deployment, with a semi-random URL. I would like to have cypress use this URL with the `CYPRESS_baseUrl` environment variable.

**Comment by bahmutov** [comment]
Can you give me more details - one job deploys to Zeit, and then it gets NOW_URL and you just need to point `CYPRESS_baseUrl=$NOW_URL`? So one job exports an environment variable and another job grabs it?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
