### ISSUE TITLE
job fail on `yarn install` because `eslint@6.1.0: The engine "node" is incompatible with this module

### ISSUE THREAD

**Issue by eloypnd** [cypress-io/circleci-orb#175]
# The orb does not work as expected

- what version of the orb are you currently using?
1.10.0
- paste the `circle.yml` file if possible or at least the relevant portion
```yml
version: 2.1
orbs:
  cypress: cypress-io/cypress@1.10.0
  slack: circleci/slack@3.2.0
executors:
  cypress-staging-integration:
    docker:
      - image: cypress/browsers:chrome69
    environment:
      CYPRESS_baseUrl: 'https://acceptphotoshoot.staginglemonone.de/'
...
workflows:
  version: 2
  deploy-staging-and-prod:
    jobs:
      - ...
      - cypress/run:
          executor: cypress-staging-integration
          requires:
            - deployStaging
          context: AcceptPsStaging
          group: 'staging'
          name: integrationTests
          no-workspace: true
          record: true
          yarn: true
...
```

- describe what you think should happen

  cypress test should run

- describe what happens

  job fail on `yarn install` because `eslint@6.1.0: The engine "node" is incompatible with this module. Expected version "^8.10.0 || ^10.13.0 || >=11.10.1".`.

<img width="1566" alt="Screen Shot 2019-09-11 at 12 21 15" src="https://user-images.githubusercontent.com/1312803/64689602-f1484280-d48e-11e9-9d8a-37fb7142c842.png">

```sh
$ #!/bin/bash -eo pipefail
yarn install --frozen-lockfile
yarn install v1.9.4
[1/4] Resolving packages...
[2/4] Fetching packages...
(node:76) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
error eslint@6.1.0: The engine "node" is incompatible with this module. Expected version "^8.10.0 || ^10.13.0 || >=11.10.1".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Exited with code 1
```

**Comment by bahmutov** [comment]
The Docker image `cypress/browsers:chrome69` is quite old - so Node version is behind there. Try using one of the newer executors https://github.com/cypress-io/circleci-orb/blob/master/docs/executors.md or Cypress Docker images https://github.com/cypress-io/cypress-docker-images

Especially since I have noticed you are not running Cypress tests in Chrome browser, so you should be good just switching to a newer Docker image with Node: https://github.com/cypress-io/cypress-docker-images/tree/master/base#cypressbase

**Comment by eloypnd** [comment]
Thanks @bahmutov!
