### ISSUE TITLE
Remove inaccessible custom badge

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/circleci-orb#182]
Top of the README file - the old badge from img.shields.io is no longer working 😟

```
[![CircleCI Orb Version](https://img.shields.io/badge/endpoint.svg?url=https://badges.circleci.io/orb/cypress-io/cypress)](https://circleci.com/orbs/registry/orb/cypress-io/cypress)
```

<img width="708" alt="Screen Shot 2019-10-07 at 1 47 35 PM" src="https://user-images.githubusercontent.com/2212006/66335522-2cf8ef80-e909-11e9-8f5c-472d18811ecc.png">

## Goal

- Remove the old badge markup
- add under the badges link to the Cypress orb page https://circleci.com/orbs/registry/orb/cypress-io/cypress

**Comment by paiva-thiago** [comment]
I'll work on it!

**Comment by iam-abbas** [comment]
May I take this up?

**Comment by lex111** [comment]
No longer relevant, this issue can be closed.

**Comment by bahmutov** [comment]
yup, seems to be resolved
