### ISSUE TITLE
CircleCI Orb certification 

### ISSUE THREAD

**Issue by SergeyVolynkin** [cypress-io/circleci-orb#206]
Greetings Cypress team,
thank you for the great plug-and-play experience with this Orb!

**I would like to raise a question about Orb certification.**

The issue is that while `cypress-io/cypress` orb being `PARTNER` certified it still requires to _'Opt-in to use of third-party orbs on your organization’s Security'(emphasis on the "Security")_. Which can be a blocker for some companies
<img width="1142" alt="Screenshot 2019-12-12 at 13 16 49" src="https://user-images.githubusercontent.com/34238697/70704059-560b7700-1ce2-11ea-94df-a717ac6cc9a1.png">

Meanwhile, AWS already has all their orbs `CERTIFIED`.
<img width="1151" alt="Screenshot 2019-12-12 at 13 16 37" src="https://user-images.githubusercontent.com/34238697/70704405-fb264f80-1ce2-11ea-96c7-332f5139bd90.png">

Maybe it's possible to do the same for such a great product as Cypress :)?

**Comment by bahmutov** [comment]
We have raised this question with CircleCI team several times, but they are dragging their feet unfortunately

**Comment by pouchyRT10** [comment]
> Greetings Cypress team,
> thank you for the great plug-and-play experience with this Orb!
> 
> **I would like to raise a question about Orb certification.**
> 
> The issue is that while `cypress-io/cypress` orb being `PARTNER` certified it still requires to _'Opt-in to use of third-party orbs on your organization’s Security'(emphasis on the "Security")_. Which can be a blocker for some companies
> <img alt="Screenshot 2019-12-12 at 13 16 49" width="1142" src="https://user-images.githubusercontent.com/34238697/70704059-560b7700-1ce2-11ea-94df-a717ac6cc9a1.png">
> 
> Meanwhile, AWS already has all their orbs `CERTIFIED`.
> <img alt="Screenshot 2019-12-12 at 13 16 37" width="1151" src="https://user-images.githubusercontent.com/34238697/70704405-fb264f80-1ce2-11ea-96c7-332f5139bd90.png">
> 
> Maybe it's possible to do the same for such a great product as Cypress :)?

+1

**Comment by valentindotxyz** [comment]
Do we have any update on this topic by any chance? 🙏

**Comment by bahmutov** [comment]
No update, unfortunately, CircleCI team has re-iterated that at this point they do not offer certification to the outside orbs

**Comment by jennifer-shehane** [comment]
closing this issue since this is outside of our control. This is dependent on CircleCI changing their certification process, so there's nothing actionable we can do right now.
