### ISSUE TITLE
Bash [[ during Mac tests

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/circleci-orb#212]
Noticed in https://circleci.com/gh/cypress-io/cypress-example-kitchensink/4347 that is using cypress-io/cypress@1.11.0 weird message

```
#!/bin/bash --login -eo pipefail
npx cypress run \
   \
   \
   --record \
     --group 'Mac build'  \
     --parallel  \
/bin/bash: [[: command not found
```
The tests continue after that

**Comment by jordanpowell88** [comment]
Closing this issue as It appears to be stale
