### ISSUE TITLE
Proposal: add a pre-install option to cypress/install

### ISSUE THREAD

**Issue by ytmagalhaes** [cypress-io/circleci-orb#232]
I noticed there is a `post-install` option that you can pass in, to run something after the build has performed the `npm ci` step.

Could we also have an option of something like `pre-install` so we can run steps before it does `npm ci` but after it does a `checkout`?
In our product we have an npm package in our `package.json` that points to a submodule like so (not the real names):
`"our-custom-package": "file:./submodules/custom-package"`

So the problem we are getting is that `cypress/install` cannot perform `npm ci` because we have no way to tell to init and sync the submodules in the project before, but after it does the `checkout` step.

If I try doing the git submodules sync step in the `pre-steps`, CircleCI reports there is no git repository (makes sense, hasn't checked out yet), and obviously the `post-steps` are even after the `post-install` so we face the problem.

If there's any other solution I would be glad to hear it. Thanks for the help!

**Comment by bahmutov** [comment]
I see, and this would be different from https://github.com/cypress-io/circleci-orb/blob/master/docs/examples.md#install-private-npm-modules step, right, since it should happen AFTER checkout but BEFORE install. Hmm, does not seem difficult to do, do you mind opening a PR with this feature?

**Comment by netochaves** [comment]
Hi, I would like to work on this issue, what part of the code should I start to look at?

**Comment by ytmagalhaes** [comment]
> I see, and this would be different from https://github.com/cypress-io/circleci-orb/blob/master/docs/examples.md#install-private-npm-modules step, right, since it should happen AFTER checkout but BEFORE install. Hmm, does not seem difficult to do, do you mind opening a PR with this feature?

Yes, that's exactly the problem! Unfortunately I don't have a computer where I can apply this fix at the moment so I will try and address it when I am able.

**Comment by ytmagalhaes** [comment]
@bahmutov thank you and apologies I was not able to do it myself.
