### ISSUE TITLE
Allow custom install command

### ISSUE THREAD

**Issue by kylemh** [cypress-io/circleci-orb#236]
**Not a bug, but a feature request!**

## What?

Allow me to use a custom install command, such as:
`yarn install --non-interactive --frozen-lockfile --production=true --cache-folder ~/.cache/yarn`

## Why?

The default command for both yarn and npm are hard-coded with a sensible default, but I'd like to be able to break out of that beyond just choosing yarn or npm. In this example, I've defined a yarn cache location that differs from the default preventing the Orb from using my dependency cache :(

**Comment by bahmutov** [comment]
Good idea, look at the src/orb file, I think it can be added there

**Comment by kylemh** [comment]
@bahmutov how should I solve this? I'm thinking of getting rid of the `yarn prop` and just adding `install_command` and defaulting to `npm ci`. It would obviously be a breaking change, but probably better than tendrilling the possibility of having `yarn` and `install_command` combined.
