### ISSUE TITLE
Add attach workspace command

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/circleci-orb#251]
To allow user-defined jobs to quickly attach the workspace created by the install job

Instead of
```
# the workspace saved by cypress/install
- attach_workspace:
    at: ~/
```

should do
```
- cypress/attach_workspace
```

**Comment by jennifer-shehane** [comment]
Closing as stale since much has changed in 3.0.0 of the orb. Please open a new issue if still experiencing an issue.
