### ISSUE TITLE
Add section with recipes

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/circleci-orb#253]
We need larger real-world examples showing how to use the orb in real situations. For example, how to install one time and then run tests in different browsers without parallel testing, or how to do semantic release after test jobs.

Good example https://github.com/bahmutov/cy-api

- installs in one job
- runs 1 test job using Electron
- runs 2nd test job using Firefox
- runs semantic release after all tests pass

all using the orb commands :)

<img width="587" alt="Screen Shot 2020-04-01 at 1 04 33 PM" src="https://user-images.githubusercontent.com/2212006/78166577-01b80e80-741b-11ea-985b-2c1d9512b81a.png">

<img width="426" alt="Screen Shot 2020-04-01 at 1 08 32 PM" src="https://user-images.githubusercontent.com/2212006/78166583-054b9580-741b-11ea-90e1-804a0f962c5f.png">

**Comment by jennifer-shehane** [comment]
I approve of the emojis 👍

**Comment by bahmutov** [comment]
@jennifer-shehane https://glebbahmutov.com/blog/example-ci-configs/#emoji
