### ISSUE TITLE
Add support / documentation for running an additional docker container alongside (e.g. a database)

### ISSUE THREAD

**Issue by paprikati** [cypress-io/circleci-orb#256]
To use this for E2E tests, I need to spin up a postgres container alongside the cypress container, so the server has something to connect to.
Is this possible with the orb? If so, can we add some docs?
Or am I thinking about this all wrong

**Comment by bahmutov** [comment]
@paprikati see the linked recipe from the pull request, points at example https://github.com/bahmutov/hasura-example with your case.

**Comment by paprikati** [comment]
Awesome! thanks for the quick turnaround
