### ISSUE TITLE
Custom run command name not being enforced

### ISSUE THREAD

**Issue by WinstonN** [cypress-io/circleci-orb#263]
Hello

I have something like this:

```
- cypress/run:
      command: |
          command 1
          command 2
```
This results in a workflow step like below

![image](https://user-images.githubusercontent.com/1143789/79516226-df6ef380-809e-11ea-8adb-e81f18151b10.png)

Can you please help me set a name for this step?

Thanks!

**Comment by bahmutov** [comment]
Try https://github.com/cypress-io/circleci-orb/releases/tag/v1.19.3
