### ISSUE TITLE
Can we halt CircleCI job if an environment variable is missing?

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/circleci-orb#297]
It would be a good way to support external pull requests that are missing an environment variable like https://github.com/bahmutov/cypress-react-unit-test/pull/320

Probably would need to pass a variable to halt the job if the variable is missing

```
if [ -n "<<parameters.variable name>>" ]; then
   echo "Skipping the Cypress job, missing environment variable <<parameters.variable name>>"
   circleci-agent step halt
fi
```

**Comment by jennifer-shehane** [comment]
Closing as stale. We haven't had issues with this specifically so I'm not sure of the priority of this work anymore.
