### ISSUE TITLE
Propose cypress/run as a command

### ISSUE THREAD

**Issue by lbesson-della** [cypress-io/circleci-orb#303]
Unless I'missing something there is no command equivalent to the run job.

In my case I would like to run a slack notification on whether the tests failed or not.

If I use the cypress/run job, the slack job cannot be run when the tests fail.
If I want to create a job that runs the test and, as final step, runs the slack command, I have a lot of code to write to match the functionality of the cypress/run job.

Having a run command almost equivalent in terms of functionalitu to the run job, that would be great

**Comment by traviscrist** [comment]
We would like this as well. It seems cypress/run is just a job so it can't be made into a reusable command. This means we have to copy the code to run the cypress/run job into multiple workflows. Having it run as a command would make things much more reusable.

**Comment by kevnm67** [comment]
Would appreciate this functionality.  I'm guessing most consumers expect this or the suggestion below with any reusable configs/orb.  It provides needed flexibility for workflows (e.g. adds a lot of user value 😎).

If not a command, thoughts on [post and pre steps, and step parameters?](https://circleci.com/docs/2.0/orbs-best-practices/#consider-post-and-pre-steps-and-step-parameters)  

Thanks for the consideration and providing this orb.

**Comment by jennifer-shehane** [comment]
Please try v3.0.0 of our orb. We have a `cypress-command` command where you pass the command to run Cypress as you normally would in a termianl. 

```
cypress-command: 'npx cypress run --record --parallel'
```

We believe this offers more flexibility which may resolve your issue. Please open a new issue if 3.0.0 does not resolve your issue.
