### ISSUE TITLE
Question about workspaces

### ISSUE THREAD

**Issue by StevenLangbroek** [cypress-io/circleci-orb#309]
## Drop Cypress stuff from workspace after tests have run

Hey folks! I noticed that while running our CircleCI pipelines, everything cypress installs as part of its orb is persisted to workspace, even after it's done running. This means that every step after our e2e tests is lugging around about 270mb of unnecessary layers. Is there a way to prevent this? I looked through the Orb but couldn't find anything. If this is behavior that should be supported I'd love to help figure out the best way to approach & submit a PR.

Thanks ❤️

**Comment by bahmutov** [comment]
Look for option skip-workspace or no-workspace - I forgot the exact name, is this what you need?

**Comment by StevenLangbroek** [comment]
Doh! That seems to be the case. Thanks Gleb!

**Comment by StevenLangbroek** [comment]
Hmmm... so, it's still carrying around the workspace layer from `cypress/install` 🤔

**Comment by bahmutov** [comment]
Can you explain the job dependencies in the workflow?

**Comment by StevenLangbroek** [comment]
![image](https://user-images.githubusercontent.com/296796/91349366-7da95d80-e7e5-11ea-9cd9-a5aef7fe59f1.png)

Does this help?

**Comment by StevenLangbroek** [comment]
@bahmutov hey! is there anything I can do to help with this?

**Comment by StevenLangbroek** [comment]
@bahmutov this is still causing performance problems in our CI pipeline. is there anything i can do to help?

**Comment by bahmutov** [comment]
I would need a better explanation of what is happening since I cannot determine from your diagram what is preserved and what is not. For example a tiny repo with a workflow file with 3 jobs (install, run, something else) and commands that show how there is an "extra" layer.

**Comment by jordanpowell88** [comment]
Going to go ahead and close this issue as it appears that there is a solution for this. Feel free to open a new issue with more a detailed description of what is happening
