### ISSUE TITLE
Please include supported Cypress versions on release notes.

### ISSUE THREAD

**Issue by giantryansaul** [cypress-io/circleci-orb#311]
Since orbs are versioned I just ran into a scenario where I updated Cypress locally and forgot to update the Cypress dependency. However, I could not figure out from the release notes which version would work. Or put another way, I couldn't tell if the latest orb would include the latest Cypress release or not.

Could you please include supported Cypress versions on the release notes for new orbs?

**Comment by bahmutov** [comment]
I am not sure I understand the problem - these orbs should be pretty compatible with all Cypress versions. Is there anything that you experience where it wasn't the case?

**Comment by bahmutov** [comment]
closing as resolved
