### ISSUE TITLE
Add support for Yarn Berry

### ISSUE THREAD

**Issue by nicholaschiang** [cypress-io/circleci-orb#312]
## The orb does not work as expected

- what version of the orb are you currently using?
  * maybe the problem has been fixed already, check the orb releases at [cypress-io/circleci-orb/releases](https://github.com/cypress-io/circleci-orb/releases)

1.26.0

- paste the `circle.yml` file if possible or at least the relevant portion

```yaml
- cypress/install
  name: 'Setup Linux'
  yarn: true
  build: yarn build:ci
  executor: with-chrome-and-firefox
```

- describe what you think should happen

Right now, I'm using Yarn Berry which exits with a deprecation error:
```
The --frozen-lockfile option is deprecated; use --immutable and/or --immutable-cache instead.
```
This is the same issue described in cypress-io/github-action#170, but here there's an easy workaround:
```yaml
- cypress/install
  install-command: yarn install --immutable --immutable-cache
```
But this orb should detect when somebody's using Yarn Berry and should automatically switch to using the new flags. See cypress-io/github-action#195 for the recommended fix.

- screenshots and links to the CircleCI builds would be great

See [this CircleCI build](https://app.circleci.com/pipelines/github/tutorbookapp/tutorbook/3/workflows/73fb2480-b40b-442e-8d09-ba7b76884133/jobs/3):

![image](https://user-images.githubusercontent.com/20798889/93026010-907aab00-f5b7-11ea-9824-b67d5814e570.png)

**Comment by bahmutov** [comment]
You can use `install-command` yourself with this Orb, see https://github.com/cypress-io/circleci-orb/blob/master/docs/jobs.md

```
- cypress/install
  name: 'Setup Linux'
  install-command: yarn install --immutable --immutable-cache
  build: yarn build:ci
  executor: with-chrome-and-firefox
```
