### ISSUE TITLE
Failed start command in run job doesn't fail job

### ISSUE THREAD

**Issue by rbabayoff** [cypress-io/circleci-orb#316]
orb version: 1.26.0

The command after, waiton, "hangs" the job:

workflows:
  test:
    jobs:
      - cypress/install:
          executor: node-12
          working_directory: packages/myapp1
          build: cd packages/myapp1 && npm run build
      - cypress/run:
          executor: node-12
          requires:
            - cypress/install
          attach-workspace: true
          working_directory: packages/myapp1
          store_artifacts: true
          start: npm start
          wait-on: "http://localhost:3000"

**Comment by amymb** [comment]
I was having this problem using react-scripts 3.4.3. I downgraded to react-scripts 3.4.0 and that solved the problem. I think react-scripts may have changed the output of the start command, and/or how it runs in the background in the more recent minor versions.

**Comment by jennifer-shehane** [comment]
Please try our new 3.0.0 version of our orb to see if this problem is still occurring. Closing as stale. Please open a new issue if you encounter something similar.
