### ISSUE TITLE
Add support for authenticating with Docker Hub to avoid rate limit

### ISSUE THREAD

**Issue by sooo-s** [cypress-io/circleci-orb#317]
https://discuss.circleci.com/t/updated-authenticate-with-docker-to-avoid-impact-of-nov-1st-rate-limits/37567

> Docker recently announced that rate limits will apply to anonymous image pulls from Docker Hub starting on November 1st, 2020. But as long as you add Docker authentication 107 to your pipeline config, you can avoid service disruption.

**Comment by rbarkley** [comment]
Alternatively, you could host the images on another host like Quay.

**Comment by jordanpowell88** [comment]
Thanks for creating the issue @sooo-s . Are you (or anyone else) currently running into the rate limit issue?

**Comment by sooo-s** [comment]
@jordanpowell88 Sorry, I do not know because I am not currently using this orb. 🙇‍♂️
