### ISSUE TITLE
Need to add a timeout to wait_on command

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/circleci-orb#319]
v1.26.0

Without a timeout, the `wait_on` waits for the default 10 minute timeout before failing without any output. If the server is exiting right away, this means 10 minute CI run just to fail. I think we could set the timeout of 1 minute and it would be enough.

**Comment by haf** [comment]
It should not be a timeout; if the concurrent process crashes, wait-on should terminate immediately.

**Comment by bahmutov** [comment]
Well since the background process might crash without circle stopping it is hard to say how to detect this in any other way

**Comment by haf** [comment]
Is it?

https://app.circleci.com/pipelines/github/logary/logary-js/548/workflows/3fe43dc2-fded-4f48-8cad-77684f5e58a4/jobs/700

This is how.

**Comment by haf** [comment]
https://github.com/kimmobrunfeldt/concurrently/blob/master/README.md#why

**Comment by bahmutov** [comment]
I am not sure what I should see here. If we start a process like using `concurrently` or `start-server-and-test` then yes. But here we are using CircleCI step and put the server in the background. How do we know if it crashed?

**Comment by haf** [comment]
I guess I'm saying that wasting 10 minutes x all the instances using this "orb", is a huge waste, when IRL it might crash after 5 seconds: so it's better not to use a separate step, and instead call through some process manager.

**Comment by bahmutov** [comment]
Sure these are two different ways of doing it

**Comment by jennifer-shehane** [comment]
The `wait-on` command has been removed from the orb in 3.0.0. Closing this issue as no longer relevant. Please open a new issue if you find yourself needing `wait-on` or encounter any other issues after upgrade.
