### ISSUE TITLE
Make this orb compatible with CircleCI RAM disk

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/circleci-orb#325]
For faster and more consistent work

See https://github.com/cypress-io/cypress-documentation/pull/3506 for use without orb

problems:
- different working directory
- specify caching for NPM and Cypress binary inside the working directory
- different attachment folder

**Comment by jordanpowell88** [comment]
According to CircleCI this is no longer a recommended feature to implement. Going to close

**Comment by phamdt** [comment]
@jordanpowell88 are you able to link where CircleCI says this?

**Comment by jordanpowell88** [comment]
@phamdt I unable to find a link for you but I believe this was something that @KyleTryon mentioned as not something they recommend. Maybe Kyle has some more context here

**Comment by KyleTryon** [comment]
This was a feature of the old CircleCI images. RAMDisk was removed after it was tested and didn't appear to actually offer any tangible benefits. The current generation of `cimg` CircleCI images does not have this option.

**Comment by jordanpowell88** [comment]
Thanks @KyleTryon
