### ISSUE TITLE
Getting error when running test case with record:true

### ISSUE THREAD

**Issue by cypress1980** [cypress-io/circleci-orb#329]
@bahmutov
I have set the CYPRESS_RECORD_KEY environment variable in Circleci project

Still getting error to Set CYPRESS_RECORD_KEY

Please help !!!!!!!!

**Comment by bahmutov** [comment]
From the original tweet

![image](https://user-images.githubusercontent.com/2212006/107553736-0ef96a00-6ba3-11eb-8605-cd4a30f365db.png)


The text says "this context", which leads me to believe you added the environment variable to a _context_ which is a collection of vars that CircleCI projects can share and import.

Unless you really use that you should set the `CYPRESS_RECORD_KEY` in a particular project's settings, like shown here

<img width="1414" alt="Screen Shot 2021-02-10 at 1 24 03 PM" src="https://user-images.githubusercontent.com/2212006/107554038-626bb800-6ba3-11eb-9102-66c57b1c33c0.png">

See more at https://circleci.com/docs/2.0/env-vars/#setting-an-environment-variable-in-a-project
