### ISSUE TITLE
A 'package-lock.json' file was not found. Please run 'npm install' in your project, and commit 'package-lock.json' to your repo.

### ISSUE THREAD

**Issue by cypress1980** [cypress-io/circleci-orb#332]
@bahmutov ,

I am getting the below error when running cypress tc in circle ci in parallel

The Cypress orb uses 'npm ci' to install 'node_modules', which requires a 'package-lock.json'.
A 'package-lock.json' file was not found. Please run 'npm install' in your project,
and commit 'package-lock.json' to your repo.

My .ymal file
![image](https://user-images.githubusercontent.com/76464201/107671939-5fafb680-6cba-11eb-816d-8bef36062f66.png)

**Comment by cypress1980** [comment]
Another screen shot
![image](https://user-images.githubusercontent.com/76464201/107672358-ccc34c00-6cba-11eb-9feb-ae9011e839e2.png)

**Comment by bahmutov** [comment]
This orb requires the repository to use a lock file like `package-lock.json` or `yarn.lock`. These lock files are recommended for consistent repeatable installations of dependencies on the CI machines. If a lock file is not found, the Orb shows an error and stops.

**Comment by Mona-Superscientist** [comment]
I'm getting this error although I've `yarn.lock` on my repo

**Comment by pitops** [comment]
any update on this? have a lock file

**Comment by myildizCH** [comment]
If you already have `package-lock.json` committed but still have this problem, follow the steps below:
• Go to the project directory
• Remove the node_modules directory: `rm -rf node_modules`.
• Remove package-lock.json file: `rm package-lock.json`
• Clear the cache: `npm cache clean --force`
• Run `npm install --verbose`
