### ISSUE TITLE
 cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync.

### ISSUE THREAD

**Issue by cypress1980** [cypress-io/circleci-orb#333]
@bahmutov 
I am getting below error even if in my project I have yarn. lock and package-lock.json

![image](https://user-images.githubusercontent.com/76464201/107773419-a3aac600-6d63-11eb-9871-de137fe0405c.png)

**Comment by cypress1980** [comment]
![image](https://user-images.githubusercontent.com/76464201/107773575-df459000-6d63-11eb-8bec-56f287347807.png)

**Comment by cypress1980** [comment]
My .yml file
![Uploading image.png…]()

**Comment by bahmutov** [comment]
Please look at the error reported. It is trying to install and is getting "Missing: osenv@^..." dependency. Maybe you have some invalid dependencies in package.json. Also, you should not mix package lock and yarn lock - you should use either one or another.
