### ISSUE TITLE
`store_artifacts` doesn't use cypress config

### ISSUE THREAD

**Issue by adam-lynch** [cypress-io/circleci-orb#349]
## The orb does not work as expected

- what version of the orb are you currently using? 1.28.0

When using `cypress/run` with `store_artifacts: true`, it uses the `working_directory` parameter if specified, but it doesn't use the Cypress config in that working directory. 

In my case. I have specified custom directories for screenshots (`screenshotsFolder`) and videos (`videosFolder`) in the config. The "Uploading artifacts" steps fail because they're not at the default location (`<< parameters.working_directory >>/cypress/videos`).

**Comment by jennifer-shehane** [comment]
Hey @adam-lynch, we just released v3.0.0 of the cypress orb where this issue may have been resolved. Even if it is not resolved however, there is an escape hatch where you would be able to pass a `--configFile` flag to our `cypress-command`, just as you would in the terminal running Cypress, and you can specify any config file for the run. 

If you still encounter an issue after upgrade, please open a new issue.
