### ISSUE TITLE
start two servers

### ISSUE THREAD

**Issue by IdanCo** [cypress-io/circleci-orb#36]
My environment requires two servers to run before testing is possible.

In the docs you provide the `start` param -
```
    - cypress/run:
        start: 'npm start'    # start server before running tests
```
Which runs the command in the background.
But how can i run *two* or more servers?

**Comment by bahmutov** [comment]
You have a couple of choices
- write a Node script or a shell command to start two servers in the background
- use a utility like [start-server-and-test](https://github.com/bahmutov/start-server-and-test) that can start both servers one by one for you, see https://github.com/bahmutov/start-server-and-test#starting-two-servers
- generate effective config https://github.com/cypress-io/circleci-orb#effective-config and replace using this orb with actual full code that you can tweak https://github.com/cypress-io/circleci-orb#ejecting
