### ISSUE TITLE
Update CircleCI Node Docker Image

### ISSUE THREAD

**Issue by emilyrohrbough** [cypress-io/circleci-orb#365]
Notice on https://circleci.com/docs/2.0/circleci-images/ reads:

> Legacy images with the prefix "circleci/" will be [deprecated](https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034) on December 31, 2021. For faster builds, upgrade your projects with [next-generation convenience images](https://circleci.com/blog/announcing-our-next-generation-convenience-images-smaller-faster-more-deterministic/).

Update `.circle.yml` to use [`cimg/node`](https://hub.docker.com/r/cimg/node).

**Comment by posva** [comment]
It would also be nice to have an updated node version. Right now, the version used, v12 is incompatible with a couple packages like lint-staged

**Comment by fasani-tx** [comment]
This was now merged. Maybe this issue can be closed.
https://github.com/cypress-io/circleci-orb/pull/376

**Comment by admah** [comment]
@fasani-tx I believe this issue is unrelated to #376.

**Comment by fasani-tx** [comment]
Agre, sorry, I copied and pasted on a few open issues which seemed related to https://github.com/cypress-io/circleci-orb/pull/376.

**Comment by admah** [comment]
No problem. Thank you for doing that!
