### ISSUE TITLE
Bump Default Node version to 14 for Cypress 12 & provide Base-18 executor

### ISSUE THREAD

**Issue by emilyrohrbough** [cypress-io/circleci-orb#388]
Bump Default Node version to 14 for Cypress 12 
- https://github.com/cypress-io/circleci-orb/blob/master/src/orb.yml#L30 
- https://github.com/cypress-io/circleci-orb/blob/master/src/orb.yml#L382
- https://github.com/cypress-io/circleci-orb/blob/master/src/orb.yml#L749

Provide base-18 executor to support node 18

**Comment by jennifer-shehane** [comment]
The default node version is now set to 16.16.0 in version 3.0.0 of the orb. Closing as resolved.
