### ISSUE TITLE
Generate a new v3 orb

### ISSUE THREAD

**Issue by jordanpowell88** [cypress-io/circleci-orb#389]
We want to create a new API for the circleCI orb to simplify the API.

- Discover how to generate a new generic orb.
- See if this can be done within the existing repo.
- Generate a new generic orb.

**Comment by jordanpowell88** [comment]
New structure can be found on branch [v3](https://github.com/cypress-io/circleci-orb/tree/v3)

**Comment by jennifer-shehane** [comment]
Published here: https://github.com/cypress-io/circleci-orb/releases/tag/v3.0.0
