### ISSUE TITLE
Add "wait-on" feature

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/circleci-orb#39]
If the server takes a while to start, we need to "wait" for the url to respond. Similar to https://github.com/bahmutov/start-server-and-test we could use `npx wait-on ...` parameter if passed to wait for the url to respond before continuing with tests

**Comment by arichter83** [comment]
FYI: I had a problem using `wait-on `without the orb see here: https://github.com/jeffbski/wait-on/issues/40
