### ISSUE TITLE
Add timeouts

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/circleci-orb#41]
For `wait-on` command and maybe for Cypress command?

Using CircleCI `no_output_timeout` option, probably do not even expose it to the user, just 5 minutes without stdout output and it is done

**Comment by elamperti** [comment]
This would be useful, I've just ran a test where `yarn start` failed and wait-on was still waiting for the server after more than 6 minutes.

**Comment by jordanpowell88** [comment]
Closing as this is a duplicate of https://github.com/cypress-io/circleci-orb/issues/316
