### ISSUE TITLE
Document using with different node version

### ISSUE THREAD

**Issue by jordanpowell88** [cypress-io/circleci-orb#425]
We need to add an example of how to change the node version. We've had several issues requesting this as a feature because it isn't well documented. 

- #424
- #423 

The example needs to go here: https://github.com/cypress-io/circleci-orb/tree/master/src/examples

**Comment by MikeMcC399** [comment]
There is now an example for Windows in https://github.com/cypress-io/cypress-realworld-app/blob/develop/.circleci/config.yml

**Comment by nagash77** [comment]
As Mike pointed out there is now an example for windows.  @jordanpowell88 are there other examples needed to close this ticket?

**Comment by jordanpowell88** [comment]
Nope we can go ahead and close

**Comment by MikeMcC399** [comment]
@jordanpowell88 

How will users reading the CircleCI documentation know that there is an example in another repository?

https://github.com/cypress-io/cypress-realworld-app/blob/develop/.circleci/config.yml

**Comment by jordanpowell88** [comment]
Good point @MikeMcC399. We should probably add this to the orb examples as well.

**Comment by nagash77** [comment]
@jordanpowell88 can you please open issue outlining those examples please?  I am going to close this issue.
