### ISSUE TITLE
Add documentation/example around using a different Node version

### ISSUE THREAD

**Issue by jordanpowell88** [cypress-io/circleci-orb#431]
The current Orb does not document well an example of how to use a different node version with the _default_ `executor`. We should create an example that will get bundled as part of the yml [examples section](https://circleci.com/developer/orbs/orb/cypress-io/cypress?utm_source=google&utm_medium=sem&utm_campaign=sem-google-dg--uscan-en-dsa-tROAS-auth-brand&utm_term=g_-_c__dsa_&utm_content=&gclid=CjwKCAjw__ihBhADEiwAXEazJjGN0SwS4cI0JTEyo3mq9fVmdSsbZu5cWvVyd7m-2vjBOmCkEUi0kxoCp1EQAvD_BwE#usage-examples)

This was discovered as part of https://github.com/cypress-io/circleci-orb/issues/425.

## The orb does not work as expected

- what version of the orb are you currently using?
  * maybe the problem has been fixed already, check the orb releases at [cypress-io/circleci-orb/releases](https://github.com/cypress-io/circleci-orb/releases)
- paste the `circle.yml` file if possible or at least the relevant portion
- describe what you think should happen
- describe what happens
  * screenshots and links to the CircleCI builds would be great

**Comment by sedghi** [comment]
seems like cypress@3 orb default node is still 16.16. Can you update that to 18? Our CI is failing after the upgrade. And the [info](https://circleci.com/developer/orbs/orb/cypress-io/cypress?utm_source=google&utm_medium=sem&utm_campaign=sem-google-dg--uscan-en-dsa-tROAS-auth-brand&utm_term=g_-_c__dsa_&utm_content#executors) on using node-version when using docker does not work 

and also the cypress@3 has deprecator using the `executor` too.

**Comment by jordanpowell88** [comment]
This PR closes this issue when it gets released
