### ISSUE TITLE
Chromedriver download returns 404

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/circleci-orb#437]
- Re-open of https://github.com/cypress-io/circleci-orb/issues/434

CircleCI is failing, for instance https://github.com/cypress-io/cypress-example-kitchensink/pull/733#issuecomment-1706376800

>Installed version of Google Chrome is 116.0.5845.140 
>116.0.5845.140 will be installed
>curl: (22) The requested URL returned error: 404 
>
>Exited with code exit status 22

A fix has been released as https://github.com/CircleCI-Public/browser-tools-orb/releases/tag/v1.4.5.

This should probably be added now to

https://github.com/cypress-io/circleci-orb/blob/d0ab66e70eff9fa7d788af3277c8b586d11f74cc/src/%40orb.yml#L11-L13

**Comment by nagash77** [comment]
This should be resolved in v3.1.4 that was released this morning.

**Comment by LeandroTorresSicilia** [comment]
This started to happening today to me in version 3.2.0

Chrome version major is 120
Installed version of Google Chrome is 120.0.6099.62 
404
Matching Chrome Driver Version 404'd, falling back to first matching major version.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   716  100   716    0     0  10447      0 --:--:-- --:--:-- --:--:-- 10529
New ChromeDriver version to be installed: 1204232
1204232 will be installed
curl: (22) The requested URL returned error: 404

Exited with code exit status 22

**Comment by MikeMcC399** [comment]
@LeandroTorresSicilia 

If your issue persists, then I suggest to open a new issue, as this one is closed.

**Comment by ArakliotisStelios** [comment]
The exact same for me

**Comment by MikeMcC399** [comment]
- See https://github.com/cypress-io/circleci-orb/issues/446
