### ISSUE TITLE
Missing ﻿cypress-io/cypress@3.2.0 in Orb Registry

### ISSUE THREAD

**Issue by sedghi** [cypress-io/circleci-orb#441]
Seems like `cypress-io/cypress@3.2.0` is not in the orb registry since we are getting this error 

![CleanShot 2023-11-01 at 11 05 17](https://github.com/cypress-io/circleci-orb/assets/7490180/42c53fc7-d7a3-4945-b5f4-e5ee00bb7e84)

Basically we are seeing some tests that are only flaky in the CI (not local) and was trying to upgrade cypress orb to see if they pass. 

My question is that is 3.1.4 based on the latest cypress version ([13.4.0](https://github.com/cypress-io/cypress/releases/tag/v13.4.0)) or it is an older version?

**Comment by jennifer-shehane** [comment]
@sedghi The Cypress version and cypress are not included in the orb itself, so it's not tied to a specific version. You are responsible for having Cypress installed, typically one might use a docker-image for this.

**Comment by sedghi** [comment]
Thanks for your reply. Also regarding version 3.2.0, which has been released in this repository under "releases." However, it seems that it is not yet available in the registry. Do you have any comments on this?

**Comment by jennifer-shehane** [comment]
@sedghi We fixed this, it's published now: https://circleci.com/developer/orbs/orb/cypress-io/cypress
