### ISSUE TITLE
CircleCI test-deploy workflow uses end-of-life Node.js 16

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/circleci-orb#448]
The CircleCI workflow [.circleci/test-deploy.yml](https://github.com/cypress-io/circleci-orb/blob/master/.circleci/test-deploy.yml) is configured to use the Docker container:

`cypress/browsers:node-16.18.1-chrome-109.0.5414.74-1-ff-109.0-edge-109.0.1518.52-1`

whereas the executor has been updated to `node-version: "20.6.0"`.

Node.js `16` already reached [end-of-life](https://nodejs.org/en/blog/announcements/nodejs16-eol/) on Sep 11, 2023 and is no longer supported.

(Runs are logged to https://app.circleci.com/pipelines/github/cypress-io/circleci-orb.)

## Suggestion

Use a minimum Node.js `18.x` version compatible with the [examples/angular-app](https://github.com/cypress-io/circleci-orb/tree/master/examples/angular-app) version installed.

**Comment by MikeMcC399** [comment]
It seems that https://app.circleci.com/pipelines/github/cypress-io/circleci-orb is not currently being triggered.

**Comment by jennifer-shehane** [comment]
@MikeMcC399 Figured it out with some help! https://github.com/cypress-io/circleci-orb/pull/449#issuecomment-1852262850

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

Thank you for taking a look at this. I can't be much help as I'm inexperienced with CircleCI and I don't have visibility into the CircleCI settings https://github.com/cypress-io/circleci-orb/settings either.

**Comment by MikeMcC399** [comment]
Since https://github.com/cypress-io/circleci-orb/blob/aa59916d55c3e6b3bc9d6aba3b2d98971e7e9e6e/examples/angular-app/package.json#L27 is currently using Angular `15`, this restricts Node.js to `^14.20.0 || ^16.13.0 || ^18.10.0` according to [Angular > Version compatibility](https://angular.io/guide/versions).

Angular `15` reaches [end-of-life](https://angular.io/guide/releases#actively-supported-versions) on May 18, 2024 so at some stage a migration to at least Angular `16` (supports Node.js `^16.14.0 || ^18.10.0`) or preferably Angular 17 (supports Node.js `^18.13.0 || ^20.9.0`) should be planned.

**Comment by jordanpowell88** [comment]
Did https://github.com/cypress-io/circleci-orb/pull/449 close this issue @jennifer-shehane ?

**Comment by MikeMcC399** [comment]
@jordanpowell88 

> Did https://github.com/cypress-io/circleci-orb/pull/449 close this issue?

- #449 is unrelated

https://github.com/cypress-io/circleci-orb/blob/master/.circleci/test-deploy.yml still contains the following usage of the now unsupported Node.js `16` version:

https://github.com/cypress-io/circleci-orb/blob/6fe76b416c2ef17123114400b3a8f337a1d4b452/.circleci/test-deploy.yml#L24-L26

https://github.com/cypress-io/circleci-orb/blob/6fe76b416c2ef17123114400b3a8f337a1d4b452/.circleci/test-deploy.yml#L35-L37

https://github.com/cypress-io/circleci-orb/blob/6fe76b416c2ef17123114400b3a8f337a1d4b452/.circleci/test-deploy.yml#L46-L48

This issue therefore remains unaddressed.
