### ISSUE TITLE
Runs failed on install chromeDriver step

### ISSUE THREAD

**Issue by ojas-krishnaprasad** [cypress-io/circleci-orb#458]
## The orb does not work as expected

- what version of the orb are you currently using?
```
orbs:
  node: circleci/node@4.3.0
  browser-tools: circleci/browser-tools@1.4.6
```
  * maybe the problem has been fixed already, check the orb releases at [cypress-io/circleci-orb/releases](https://github.com/cypress-io/circleci-orb/releases)
- paste the `circle.yml` file if possible or at least the relevant portion
```
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
```
- describe what you think should happen
![2024-02-17_01-45](https://github.com/cypress-io/circleci-orb/assets/121866566/552ab664-d3f0-4f55-92df-5dca311fd0d8)

- describe what happens

  * screenshots and links to the CircleCI builds would be great
![2024-02-17_01-44](https://github.com/cypress-io/circleci-orb/assets/121866566/b97ad121-8583-4779-8735-c1f4a18e7b9a)

**Comment by jennifer-shehane** [comment]
@ojas-krishnaprasad Is this still occurring? The chrome driver URL is not really under our control.

**Comment by ojas-krishnaprasad** [comment]
Yes, it was still, You can check this url [https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.184/linux64/chromedriver-linux64.zip](https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.184/linux64/chromedriver-linux64.zip) as per circle Ci scripts to download the driver

**Comment by ojas-krishnaprasad** [comment]
Linking the issue to another repo https://github.com/CircleCI-Public/browser-tools-orb/issues/102

**Comment by jennifer-shehane** [comment]
Yah, we're seeing the same issue in one of our own repos using the orb: https://app.circleci.com/pipelines/github/cypress-io/cypress-example-kitchensink/1749/workflows/fbed68d8-aeb8-4df2-b182-7f9ced5e425b/jobs/12032 Looks like there's potentially an issue with the browsers-tools-orb from the link, which we rely on.

**Comment by ojas-krishnaprasad** [comment]
This was solved with this https://github.com/CircleCI-Public/browser-tools-orb/pull/105, So closing this Issue.

**Comment by jennifer-shehane** [comment]
Please update to cypress' 3.3.1 orb to get this fix: https://github.com/cypress-io/circleci-orb/releases/tag/v3.3.1
