### ISSUE TITLE
Previous release v3.2.1 marked as latest

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/circleci-orb#461]
Although [CircleCI Orbs > cypress-io/cypress](https://circleci.com/developer/orbs/orb/cypress-io/cypress) shows `cypress-io/cypress@3.3.0` version published on Jan 16, 2024, the [GitHub releases section](https://github.com/cypress-io/circleci-orb/releases) still shows the previous version [v3.2.1](https://github.com/cypress-io/circleci-orb/releases/tag/v3.2.1) tagged as `Latest`.

Please tag [v3.3.0](https://github.com/cypress-io/circleci-orb/releases/tag/v3.3.0) as `Latest` in the [GitHub releases section](https://github.com/cypress-io/circleci-orb/releases).

cc: @jordanpowell88

**Comment by jennifer-shehane** [comment]
Updated https://github.com/cypress-io/circleci-orb/releases
