### ISSUE TITLE
How do you clear cache with an Orb?

### ISSUE THREAD

**Issue by danawoodman** [cypress-io/circleci-orb#48]
Circle is not picking up my dependency changes and I see no way to clear the cache from the config file or the UI. Thanks!

**Comment by bahmutov** [comment]
Is the package-lock.json updated?

**Comment by bahmutov** [comment]
@danawoodman can you provide more details?

**Comment by danawoodman** [comment]
Sorry, this is more of a question for CircleCI since their UX around clearing caches is terrible. Sorry!
