### ISSUE TITLE
pnpm example failure blocks ability to release new orb

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/circleci-orb#493]
- As noted in PR #492 the current master branch is failing on a release attempt of `cypress-io/cypress@3.4.1`.

- The tag [v3.4.1](https://github.com/cypress-io/circleci-orb/tree/v3.4.1) has been created,  https://circleci.com/developer/orbs/orb/cypress-io/cypress however shows `cypress-io/cypress@3.4.0` as current version.

---

https://app.circleci.com/pipelines/github/cypress-io/circleci-orb/1980/workflows/d6852e7e-67f2-4268-bc7e-ecf6f4e14169

![test deploy fail](https://github.com/user-attachments/assets/78096698-c5aa-49cf-a117-3f75b2da41c9)

In Pnpm Example
Installing PNPM packages

```text
WARN  Ignoring not compatible lockfile at /home/circleci/project/examples/pnpm-install/pnpm-lock.yaml
node_modules/.pnpm                       |  WARN  Ignoring not compatible lockfile at /home/circleci/project/examples/pnpm-install/node_modules/.pnpm/lock.yaml
 ERR_PNPM_NO_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is present

Note that in CI environments this setting is true by default. If you still need to run install in such cases, use "pnpm install --no-frozen-lockfile"

Exited with code exit status 1
```

Previously however in https://app.circleci.com/pipelines/github/cypress-io/circleci-orb/1979/workflows/bb9d6442-3348-4e0b-9e24-a68534062542 merging into `master` the test was successful:

![test deploy succeed](https://github.com/user-attachments/assets/3460df72-5037-46e1-982b-f649930e6ee7)

**Comment by MikeMcC399** [comment]
@ramykl 

Do you know why this is failing and are you able to fix it?

**Comment by MikeMcC399** [comment]
- See #494 for workaround

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

- Now that PR https://github.com/cypress-io/circleci-orb/pull/494 is successfully merged, you might like to try once again to release a new version of the Orb.

**Comment by jennifer-shehane** [comment]
This is released now
