### ISSUE TITLE
[Question] Config for projects created with vue-cli

### ISSUE THREAD

**Issue by mornir** [cypress-io/circleci-orb#60]
Hi!
I created a [basic project](https://github.com/mornir/tdd-monster-slayer) with Vue-CLI 3 and I added [two tests](https://github.com/mornir/tdd-monster-slayer/tree/master/tests/e2e/specs):
- One E2E test
- One unit test with `cypress-vue-unit-test`.

Using the [simple circle.yml config](https://github.com/mornir/tdd-monster-slayer/blob/master/circle.yml), the unit test passes, but the E2E test fails:
![image](https://user-images.githubusercontent.com/1411843/50374180-bfced480-05ea-11e9-8ba4-51e18285022f.png)
https://circleci.com/gh/mornir/tdd-monster-slayer/9

I guess I need to start the Vue app so Cypress can visit it?
I've tried all sorts of npm commands in the circle.yml, but none worked.

I am new to continuous integration and my mistake must be obvious to more experienced developers...
I was kind of expecting for everything to be working magically out the box 😅

**Comment by mornir** [comment]
Okay, I found out what was wrong.

Vue-CLI automatically sets the correct base URL for the test. So when I launch `npm test` and invoke the command `cy.visit("/")`, Cypress visits the right URL. But for it to work on circleci, I had to explicitly set a global baseURL in `cypress.json`, [as it is recommended in the docs](https://docs.cypress.io/guides/references/best-practices.html#Setting-a-global-baseUrl). Actually had I done that before, I would have gotten a better error message.

Then I use the following config for circleci:
```yml
version: 2.1
orbs:
  cypress: cypress-io/cypress@1.1.0
workflows:
  build:
    jobs:
      - cypress/run:
          start: npm run serve
          wait-on: 'http://localhost:8080'
``` 
I noticed that it also works if I don't use the `wait-on` command, but [Cypress docs recommend using it](https://docs.cypress.io/guides/guides/continuous-integration.html#Boot-your-server).

Happy to have finally gotten that green build on circleci 😎

**Comment by mornir** [comment]
Done 😃 Just one question: 
If I write `cypress-io/cypress@1`, will I automatically get the latest major version?

**Comment by bahmutov** [comment]
With `cypress-io/cypress@1` you will get the latest version `1.x.y` of our orb. When we change the orb in a breaking way, we will publish version `cypress-io/cypress@2.0.0` and you will NOT get it, you will still stay on the last available version of `1.x.y`, see https://circleci.com/docs/2.0/creating-orbs/#semantic-versioning-in-orbs
