### ISSUE TITLE
Use --frozen-lockfile when installing with yarn

### ISSUE THREAD

**Issue by pschlette** [cypress-io/circleci-orb#72]
Currently, when the `cypress/install` job is using `npm`, the command `npm ci` is used to install packages. The [npm-ci docs](https://docs.npmjs.com/cli/ci.html) note that
> If dependencies in the package lock do not match those in package.json, npm ci will exit with an error, instead of updating the package lock.

which makes sense in a CI environment.

By contrast, when `yarn` is being used, the command `yarn install` is used to install packages, which will happily update `yarn.lock` if it doesn't match with `package.json`. Per the [yarn install docs](https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-frozen-lockfile), the `--frozen-lockfile` flag is needed to get similar behavior to `npm ci`, in the sense of requiring that the `package.json` and the lockfile are in agreement.

Could `--frozen-lockfile` be added to the `yarn install` command or made configurable with a parameter so that the build will fail if `package.json` and the lockfile disagree, like when npm is used?

**Comment by bahmutov** [comment]
great suggestion @pschlette - if you have time to make a PR with the Orb change and updated description in the example, I would gladly merge it and release new version
