### ISSUE TITLE
`wait-on` doesn't support Cypress's non-strict SSL feature

### ISSUE THREAD

**Issue by jalada** [cypress-io/circleci-orb#90]
I'm taking advantage of Cypress's ability to support HTTPS testing with an invalid certificate, but I'm also using the `wait-on` feature in this orb. However `wait-on` by default requires a valid SSL certificate.

I mitigated this by creating a `.circleci/wait-on-config.json` that looks like:

```json
{
  "strictSSL": false
}
```

and then changing my `config.yml`:

```yaml
wait-on: '-c .circleci/wait-on-config.json https://localhost:3000'
```

This is a little quirky, as the documentation says the parameter should be the host, but I'm taking advantage of the fact that you're just tacking the configuration on the end of the command.

I'm not saying non-strictSSL should be the default, but I think it'd be great to have an officially recommended way of dealing with this. Even if it's just updating the documentation to indicate you can pass all options to `wait-on` in the YAML like I am.

Alternatively you can tell `wait-on` to wait for a `socket` to be ready, but I like the fact that telling `wait-on` to use HTTP(S) makes it check for a 2xx response too.

**Comment by bahmutov** [comment]
nice addition, I should add this to the README examples

**Comment by alxndr** [comment]
Trying to set Cypress up on CircleCI now to test a web project that runs via SSL — Does this trick still work?
