### ISSUE TITLE
How to build and start app depending on docker setup

### ISSUE THREAD

**Issue by justin808** [cypress-io/circleci-orb#92]
I've got a setup for running my app, a Ruby on Rails app:

1. Docker container for Postgres
2. Docker container for Ruby + Node version + Yarn version
3. Cached dependencies saved from prior build steps including the global ~/.cache

How do I start the server that Cypress will hit if the server depends on these dependencies? There doesn't seem to be a way to leverage the caches and docker containers that I've setup. 

Is using an Orb correct for my use case?

Or should I fork the orb?

Can I modify a docker setup and use my own docker image?

**Comment by bahmutov** [comment]
Hmm, this seems like a more complex use case that this orb is meant to solve, @justin808 unfortunately

**Comment by michelle-luna** [comment]
copying @iynere in case she can help out

**Comment by iynere** [comment]
@justin808 i didn't write this orb, but I work on orbs for CircleCI... if you post a more detailed explanation of your use case on [Discuss](https://discuss.circleci.com/c/orbs), with links to jobs where you've tried it out, i or a teammate or folks from Cypress may be able to better assist

**Comment by justin808** [comment]
I posted here: https://discuss.circleci.com/t/using-custom-docker-setups-with-orbs/28566
